<?php
	// Site labels
	define("SITE_NAME", "Temporary AppletLand/Lostfacts Home");
	define("RANK_POINTS", "Aura");
	define("CURRENCY", "Jizz");

	// Staff userlevels
	define("ADMIN_LEVEL", 100);
	define("ELITE_MOD_LEVEL", 80);
	define("MOD_LEVEL", 70);
	
	// Temporary Userlevels - Revert to normal once unwarntime is reached
	define("PROVISIONAL", 5);
	define("PROBATION", 3);
	define("TIMED_SUS", 2);
	define("PENDING_CLOSE", -3);

	// Board permissions
	define("POSTING_LEVEL", 3);
	define("TOPIC_MAKING_LEVEL", 5);
	define("BASE_LVL", 20);
	
	// Miscellaneous
	define("MAX_APPOINT_LVL", 59);
	define("MIN_APPOINT_LVL", 4);
	define("LOCKED", 1);
	define("CLOSED", -4);
	define("DENIED", -5);
	define("SUSPENDED", -1);
	define("BANNED", -2);
	define("INACTIVE", 0);